name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
         echo "${{ secrets.DOCKER }}" | docker login -u "madhavkrishna118" --password-stdin
         docker image build -t madhavkrishna118/dockergithub:v2 .
         docker push madhavkrishna118/dockergithub:v2
